use auditor_db::DbPool;
use auditor_db::queries::{events::get_events, sessions::get_sessions};
use serde_json::json;
use std::sync::Arc;
use uuid::Uuid;
use anyhow::Result;
use tera::{Context, Tera};

#[derive(Debug, Clone, Copy)]
pub enum ReportFormat {
    Html,
    Pdf,
    Markdown,
    Json,
}

impl ReportFormat {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "html" => Some(ReportFormat::Html),
            "pdf" => Some(ReportFormat::Pdf),
            "markdown" | "md" => Some(ReportFormat::Markdown),
            "json" => Some(ReportFormat::Json),
            _ => None,
        }
    }
}

const HTML_TEMPLATE: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>CCAudit Report — {{ generated_at }}</title>
<style>
body { font-family: -apple-system, sans-serif; max-width: 1100px; margin: 2rem auto; color: #1f2937; padding: 0 2rem; }
h1 { color: #111827; border-bottom: 2px solid #3b82f6; padding-bottom: .5rem; }
h2 { color: #1f2937; margin-top: 2.5rem; }
.meta { background: #f3f4f6; padding: 1rem 1.5rem; border-radius: 8px; margin: 1rem 0 2rem; }
.stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin: 2rem 0; }
.stat { background: #fff; border: 1px solid #e5e7eb; padding: 1rem; border-radius: 8px; }
.stat-label { color: #6b7280; font-size: .85rem; text-transform: uppercase; }
.stat-value { color: #111827; font-size: 1.75rem; font-weight: 700; margin-top: .25rem; }
table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
th, td { text-align: left; padding: .6rem .8rem; border-bottom: 1px solid #e5e7eb; font-size: .9rem; }
th { background: #f9fafb; color: #374151; font-weight: 600; }
.badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: .75rem; font-weight: 600; }
.high { background: #d1fae5; color: #047857; }
.ambiguous { background: #fef3c7; color: #b45309; }
.verified { background: #dbeafe; color: #1e40af; }
.footer { margin-top: 3rem; color: #9ca3af; font-size: .8rem; text-align: center; padding-top: 1rem; border-top: 1px solid #e5e7eb; }
code { font-family: ui-monospace, monospace; font-size: .85em; background: #f3f4f6; padding: 1px 5px; border-radius: 3px; }
</style>
</head>
<body>
<h1>CCAudit Report</h1>
<div class="meta">
  <strong>Generated:</strong> {{ generated_at }}<br>
  <strong>Sessions analyzed:</strong> {{ session_count }}<br>
  <strong>Total events:</strong> {{ event_count }}
</div>

<div class="stats">
  <div class="stat"><div class="stat-label">Tool Sessions</div><div class="stat-value">{{ session_count }}</div></div>
  <div class="stat"><div class="stat-label">Audit Events</div><div class="stat-value">{{ event_count }}</div></div>
  <div class="stat"><div class="stat-label">Unique Tools</div><div class="stat-value">{{ unique_tools }}</div></div>
  <div class="stat"><div class="stat-label">High Confidence</div><div class="stat-value">{{ high_confidence }}</div></div>
</div>

<h2>Sessions</h2>
{% if sessions | length > 0 %}
<table>
<thead><tr><th>Tool</th><th>PID</th><th>Started</th><th>Confidence</th></tr></thead>
<tbody>
{% for s in sessions %}
<tr>
  <td><strong>{{ s.tool_id }}</strong></td>
  <td><code>{{ s.pid }}</code></td>
  <td>{{ s.started_at }}</td>
  <td><span class="badge {{ s.confidence | lower }}">{{ s.confidence }}</span></td>
</tr>
{% endfor %}
</tbody>
</table>
{% else %}
<p>No sessions in this report.</p>
{% endif %}

<h2>Events</h2>
{% if events | length > 0 %}
<table>
<thead><tr><th>Time</th><th>Kind</th><th>Path / Address</th><th>Confidence</th></tr></thead>
<tbody>
{% for e in events %}
<tr>
  <td>{{ e.timestamp }}</td>
  <td>{{ e.kind }}</td>
  <td><code>{{ e.detail }}</code></td>
  <td><span class="badge {{ e.confidence | lower }}">{{ e.confidence }}</span></td>
</tr>
{% endfor %}
</tbody>
</table>
{% else %}
<p>No events recorded for these sessions.</p>
{% endif %}

<div class="footer">
  CCAudit v0.1.0 · Generated by Masudur Rahman · <em>Local-first AI tool auditor</em>
</div>
</body>
</html>"#;

const MARKDOWN_TEMPLATE: &str = r#"# CCAudit Report

**Generated:** {{ generated_at }}
**Sessions analyzed:** {{ session_count }}
**Total events:** {{ event_count }}
**Unique tools:** {{ unique_tools }}

## Sessions

{% if sessions | length > 0 %}
| Tool | PID | Started | Confidence |
|------|-----|---------|------------|
{% for s in sessions %}| {{ s.tool_id }} | {{ s.pid }} | {{ s.started_at }} | {{ s.confidence }} |
{% endfor %}
{% else %}
_No sessions in this report._
{% endif %}

## Events

{% if events | length > 0 %}
| Time | Kind | Path / Address | Confidence |
|------|------|----------------|------------|
{% for e in events %}| {{ e.timestamp }} | {{ e.kind }} | `{{ e.detail }}` | {{ e.confidence }} |
{% endfor %}
{% else %}
_No events recorded._
{% endif %}

---

_CCAudit v0.1.0 · Local-first AI tool auditor_
"#;

pub async fn generate(
    db: Arc<DbPool>,
    session_ids: Vec<Uuid>,
    format: ReportFormat,
) -> Result<Vec<u8>> {
    // Fetch all sessions, then filter to requested IDs
    let all_sessions = get_sessions(&db, 1000)?;
    let filtered_sessions: Vec<_> = if session_ids.is_empty() {
        all_sessions
    } else {
        all_sessions
            .into_iter()
            .filter(|s| session_ids.contains(&s.id))
            .collect()
    };

    // Fetch events for each session
    let mut all_events = Vec::new();
    for session in &filtered_sessions {
        let evs = get_events(&db, session.id, 5000)?;
        all_events.extend(evs);
    }

    // Compute stats
    let unique_tools: std::collections::HashSet<_> =
        filtered_sessions.iter().map(|s| s.tool_id.0.clone()).collect();
    let high_confidence = filtered_sessions
        .iter()
        .filter(|s| matches!(s.confidence, auditor_core::tool::Confidence::High))
        .count();

    let now = chrono::Local::now().format("%Y-%m-%d %H:%M:%S %Z").to_string();

    // Format sessions for template
    let sessions_view: Vec<_> = filtered_sessions
        .iter()
        .map(|s| {
            json!({
                "tool_id": s.tool_id.0,
                "pid": s.pid,
                "started_at": s.started_at.to_string(),
                "confidence": format!("{:?}", s.confidence),
            })
        })
        .collect();

    // Format events for template
    let events_view: Vec<_> = all_events
        .iter()
        .map(|e| {
            let (kind, detail) = match &e.kind {
                auditor_core::events::EventKind::FsRead { path } => ("fs_read", path.clone()),
                auditor_core::events::EventKind::FsWrite { path } => ("fs_write", path.clone()),
                auditor_core::events::EventKind::FsDelete { path } => ("fs_delete", path.clone()),
                auditor_core::events::EventKind::NetConnect { addr, port, .. } => {
                    ("net_connect", format!("{}:{}", addr, port))
                }
                auditor_core::events::EventKind::ProcessSpawn { exe, .. } => {
                    ("process_spawn", exe.clone())
                }
                auditor_core::events::EventKind::LocalArtifact { path, .. } => {
                    ("local_artifact", path.clone())
                }
            };
            json!({
                "timestamp": e.timestamp.to_string(),
                "kind": kind,
                "detail": detail,
                "confidence": format!("{:?}", e.confidence),
            })
        })
        .collect();

    // Build context
    let mut ctx = Context::new();
    ctx.insert("generated_at", &now);
    ctx.insert("session_count", &filtered_sessions.len());
    ctx.insert("event_count", &all_events.len());
    ctx.insert("unique_tools", &unique_tools.len());
    ctx.insert("high_confidence", &high_confidence);
    ctx.insert("sessions", &sessions_view);
    ctx.insert("events", &events_view);

    match format {
        ReportFormat::Json => {
            let report = json!({
                "generated_at": now,
                "session_count": filtered_sessions.len(),
                "event_count": all_events.len(),
                "unique_tools": unique_tools.len(),
                "high_confidence": high_confidence,
                "sessions": sessions_view,
                "events": events_view,
            });
            Ok(serde_json::to_vec_pretty(&report)?)
        }
        ReportFormat::Html => {
            let mut tera = Tera::default();
            tera.add_raw_template("report.html", HTML_TEMPLATE)?;
            let rendered = tera.render("report.html", &ctx)?;
            Ok(rendered.into_bytes())
        }
        ReportFormat::Markdown => {
            let mut tera = Tera::default();
            tera.add_raw_template("report.md", MARKDOWN_TEMPLATE)?;
            let rendered = tera.render("report.md", &ctx)?;
            Ok(rendered.into_bytes())
        }
        ReportFormat::Pdf => {
            // For now, render HTML and document that PDF requires external conversion
            let mut tera = Tera::default();
            tera.add_raw_template("report.html", HTML_TEMPLATE)?;
            let rendered = tera.render("report.html", &ctx)?;
            // Note: a full PDF implementation would use printpdf or headless Chrome
            // For now, return HTML with instruction
            Ok(rendered.into_bytes())
        }
    }
}
